services:
  apache:
    image: 'defconjuan/docker-php-5.5'
    container_name: php
    restart: always
    ports:
      - '80:80'
    volumes:
      - ./html:/var/www/html
    depends_on:
      - db
    links:
      - db
      
db:
  image: mariadb:10.3.10
  restart: always
  volumes:
    - ./mysql:/var/lib/mysql
  environment:
    MYSQL_ROOT_PASSWORD: root
    MYSQL_USER: admin
    MYSQL_PASSWORD: test
    MYSQL_DATABASE: bancodedados
  ports:
    - "8889:3306"
    

    
