web:
    image: 'webimp/php-55-apache'
    restart: always
    ports:
      - '8080:8080'
    volumes:
      - ./html:/var/www/html
    links:
      - mariadb
      
mariadb:
  image: mariadb:10.3.10
  restart: always
  volumes:
    - ./mysql:/var/lib/mysql
  environment:
    MYSQL_ROOT_PASSWORD: root
    MYSQL_USER: admin
    MYSQL_PASSWORD: test
    MYSQL_DATABASE: bancodedados
  ports:
    - "8889:3306"
    
phpmyadmin:
  image: phpmyadmin/phpmyadmin
  container_name: phpmyadmin
  environment:
    - PMA_ARBITRARY=1
    - PMA_HOST=mariadb
  restart: always
  ports:
    - 80:80
  volumes:
    - /sessions
  links:
    - mariadb
    
